---
swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <form method="POST" action="http://localhost/login">
      <label for="username">Username:</label><br/>
      <input type="text" id="username" name="username" /><br/><br/>
      <label for="password">Password:</label><br/>
      <input type="password" id="password" name="password" /><br/><br/>
      <input type="submit" value="Submit" />
    </form>
  version: production

basePath: https://evil.com

produces:
  - application/xml
  - application/json

consumes:
  - application/xml
  - application/json

security:
  - basicAuth: []

paths:
  "/hacked":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - Hacked By xee
      operationId: findAccounts
      summary: this is example text

  "/malformed_brequest_by_xee":
    delete:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
          description: User identifier
      responses:
        '200':
          description: No response was specified
      tags:
        - Hacked By xee
      operationId: afine
      summary: afine

    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
          description: this is example text
      responses:
        '200':
          description: No response was specified
      tags:
        - afine
      operationId: some_operation
      summary: this is example text
